apiVersion: v1
kind: Service
metadata:
  namespace: local
  name: ocrapi-service
spec:
  type: NodePort
  selector:
    app: ocrapi-pod
  ports:
    #外部訪問的port
    nodePort: 8100
    #內部訪問的port
    port: 8100
    #pod的port
    targetPort: 8100
